# left prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

# right prompt
right_format = """
$bun\
$container\
$direnv\
$nix_shell\
$package\
$python\
$rust\
"""

# continuation prompt (for interactive lines)
continuation_prompt = ''

# adds a newline inbetween shell prompts
add_newline = true

[username]
style_user = 'green bold'
style_root = 'red bold'

[hostname]
ssh_only = false
ssh_symbol = "ğŸŒ "
style = 'green dimmed bold'

[directory]
truncation_length = 3 # max number of parent directories
truncation_symbol = ''
truncate_to_repo = true # truncate path to parent git repo
style = "blue"
read_only = "ğŸ”’" # symbol to show when directory is read only
read_only_style = "red"

[git_branch]
symbol = ""
style = "bright-black"
format = "on [$symbol$branch(:$remote_branch)]($style) "

[git_status]
format = "[[($all_status)](bright-magenta) ($ahead_behind)]($style) "
style = "cyan"
# part of $all_status (in order)
conflicted = "â€‹"
stashed = "â‰¡"
deleted = "â€‹"
renamed = "â€‹"
modified = "â€‹"
staged = "â€‹"
untracked = "â€‹"
# part of $ahead_behind (one of below)
diverged = "â‡•"
ahead = "â‡¡"
behind = "â‡£"
up_to_date = ""

[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"

# UNIQUE --------------------------------------------------------------
[bun]
format = "via [$symbol($version)]($style) "
symbol = "ğŸ¥Ÿ "
style = "bold red"

# if inside a container, display this
[container]
symbol = "â¬¢"
style = "red bold dimmed"
format = "[$symbol [$name]]($style) "

# if direnv rc file exists, display this
[direnv]
format = "[$symbol$loaded/$allowed]($style) "
symbol = "direnv "
style = "bold bright-yellow"
loaded_msg = "loaded"
unloaded_msg = "not loaded"
allowed_msg = "allowed"
not_allowed_msg = "not allowed"
denied_msg = "denied"

# if currently in a nix dev shell, display this
[nix_shell]
format = "via [$symbol$state($name)]($style) "
symbol = "â„ï¸  "
style = "bold blue"
impure_msg = "impure"
pure_msg = "pure"

# general purpose package module (supports cargo, npm, python, and some others)
[package]
format = "is [$symbol$version]($style) "
symbol = "ğŸ“¦ "
style = "208 bold"

[python]
format = "via [$symbol($version)($virtualenv)]($style) "
symbol = "ğŸ "
style = "yellow bold"

[rust]
format = "via [$symbol($version)]($style) "
symbol = "ğŸ¦€ "
style = "bold red"
